# Generated by Django 3.0.3 on 2020-02-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_num', models.AutoField(db_column='company_num', primary_key=True, serialize=False)),
                ('member_name', models.CharField(db_column='member_name', max_length=200)),
                ('company_addr', models.CharField(db_column='company_addr', max_length=200)),
                ('company_phone', models.CharField(db_column='company_phone', max_length=200)),
                ('bicycle_num', models.IntegerField(db_column='bicycle_num')),
                ('member_id', models.CharField(db_column='member_id', max_length=200)),
                ('s_business', models.DateTimeField(db_column='s_business')),
                ('e_business', models.DateTimeField(db_column='e_business')),
                ('company_info', models.CharField(db_column='company_info', max_length=1000)),
                ('company_loc', models.CharField(db_column='company_loc', max_length=200)),
                ('rent_num', models.IntegerField(db_column='rent_num')),
            ],
            options={
                'db_table': 'company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Counsel',
            fields=[
                ('counsel_num', models.AutoField(db_column='counsel_num', primary_key=True, serialize=False)),
                ('member_id', models.CharField(db_column='member_id', max_length=50)),
                ('regdate', models.DateTimeField(db_column='regdate')),
                ('subject', models.CharField(db_column='subject', max_length=200)),
                ('content', models.CharField(db_column='content', max_length=1000)),
                ('category', models.IntegerField(db_column='category')),
            ],
            options={
                'db_table': 'counsel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('c_num', models.AutoField(db_column='c_num', primary_key=True, serialize=False)),
                ('c_name', models.CharField(db_column='c_name', max_length=200)),
                ('c_info', models.TextField(db_column='c_info', max_length=1000)),
                ('c_loc', models.CharField(db_column='c_loc', max_length=200)),
                ('c_theme', models.CharField(db_column='c_theme', max_length=200)),
                ('c_time', models.IntegerField(db_column='c_time')),
            ],
            options={
                'db_table': 'course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('history_num', models.AutoField(db_column='history_num', primary_key=True, serialize=False)),
                ('company_num', models.IntegerField(db_column='company_num')),
                ('member_id', models.CharField(db_column='member_id', max_length=200)),
                ('r_btime', models.DateTimeField(db_column='r_btime')),
                ('btime', models.DateTimeField(db_column='btime', default='1970-01-02 00:00')),
                ('r_rtime', models.DateTimeField(db_column='r_rtime')),
                ('rtime', models.DateTimeField(db_column='rtime', default='1970-01-02 00:00')),
                ('reserved_At', models.DateTimeField(db_column='reserved_At')),
                ('barcode', models.CharField(db_column='barcode', max_length=50)),
            ],
            options={
                'db_table': 'history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('num', models.AutoField(db_column='num', primary_key=True, serialize=False)),
                ('writer', models.CharField(db_column='writer', max_length=50)),
                ('regdate', models.DateTimeField(db_column='regdate')),
                ('subject', models.CharField(db_column='subject', max_length=200)),
                ('content', models.CharField(db_column='content', max_length=1000)),
            ],
            options={
                'db_table': 'notice_board',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Refer',
            fields=[
                ('counsel_num', models.IntegerField(db_column='counsel_num', primary_key=True, serialize=False)),
                ('regdate', models.DateTimeField(db_column='regdate')),
                ('content', models.CharField(db_column='content', max_length=1000)),
                ('refer_admin', models.CharField(db_column='refer_admin', max_length=50)),
            ],
            options={
                'db_table': 'refer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(db_column='id', max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=200)),
                ('pwd', models.CharField(db_column='pwd', max_length=200)),
                ('info', models.IntegerField(db_column='info')),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
